import type { NextPage } from "next";
import Head from "next/head";
import { CircularBar } from "../components/circular-bar";
import { Header } from "../components/header";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>veg.co</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
      </main>
    </div>
  );
};

export default Home;
