apiVersion: batch/v1
kind: CronJob
metadata:
  name: products-population
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: populateTable.py
              image: beavanzi/populateTable.py:{version-fake}
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo CronJob executado
          restartPolicy: OnFailure
