# Generated by Django 4.0.4 on 2022-04-13 13:00

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=60)),
                ('number', models.CharField(max_length=8)),
                ('complement', models.CharField(max_length=60)),
                ('ZIP', models.CharField(max_length=8)),
                ('neighborhood', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('password', django_cryptography.fields.encrypt(models.CharField(max_length=64))),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.address')),
                ('clickedAds', models.ManyToManyField(to='core.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGPG', 'Aguardando Pagamento'), ('PGCF', 'Pagamento Confirmado'), ('ENVI', 'Enviado'), ('FINA', 'Finalizado'), ('CANC', 'Cancelado')], default='AGPG', max_length=4)),
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.consumer')),
                ('product', models.ManyToManyField(to='core.product')),
            ],
        ),
    ]
