# Generated by Django 4.0.4 on 2022-04-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ad_address_consumer_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='cpf',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='email',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
