# Generated by Django 4.0.4 on 2022-04-13 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
        ('core', '0003_consumer_cpf_alter_consumer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='clickedAds',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='consumer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consumer.consumer'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
    ]
